export const ABOUT_TRANSLATIONS = {
  en: {
    'about.badge': 'ABOUT WEATHERGPT', 'about.title': 'Your intelligent companion for understanding the weather', 'about.intro': 'WeatherGPT is a modern, AI-powered weather platform that makes weather information easier to understand and use.', 'about.detail': 'Instead of navigating through complicated weather data, WeatherGPT brings forecasts, weather alerts, location-based insights, climate information, and conversational AI together in one simple platform.', 'about.what': 'What You Can Do with WeatherGPT', 'about.forecasts': 'Get Weather Forecasts', 'about.forecastsBody': 'Check current weather conditions and upcoming forecasts for your location.', 'about.questions': 'Ask Weather Questions', 'about.questionsBody': 'Ask questions about rain, clothing, travel or safety in simple words.', 'about.locations': 'Location-Based Weather Insights', 'about.locationsBody': 'Select a location and receive weather information and risk insights for that area.', 'about.alerts': 'Stay Aware with Weather Alerts', 'about.alertsBody': 'Receive information about severe weather conditions and possible hazards.', 'about.maps': 'Explore Weather on Maps', 'about.mapsBody': 'Use maps to explore places and understand weather conditions geographically.', 'about.climate': 'Discover Climate Information', 'about.climateBody': 'Learn about climate patterns, rainfall, seasons and other weather information.', 'about.designed': 'Designed Around You', 'about.designedBody': 'WeatherGPT combines weather data and artificial intelligence to turn complex meteorological information into clear and useful insights.', 'about.designedBody2': 'Whether you are planning your day, preparing for travel or monitoring changing weather, WeatherGPT helps you understand what matters.', 'about.vision': 'Our Vision', 'about.visionQuote': 'Make weather information simple, accessible and actionable for everyone.', 'about.visionBody': 'WeatherGPT brings reliable weather information into a conversational experience so users can spend less time interpreting data and more time making informed decisions.', 'about.footer': 'WeatherGPT - Understand the weather. Plan with confidence.',
    'footer.climateData': 'Climate data: Open-Meteo Historical Weather API (ERA5)', 'footer.aiDetail': 'Google Gemini when available; WeatherGPT rule-based mode otherwise', 'footer.safety': 'Safety information', 'footer.safetyAutomated': 'Automated assessments are not official warnings.', 'footer.safetyAuthorities': 'Follow local authority instructions during severe weather.', 'footer.safetyIndia': 'For India, check IMD and NDMA updates.',
  },
  hi: {
    'about.badge': 'वेदरGPT के बारे में', 'about.title': 'मौसम समझने में आपका बुद्धिमान साथी', 'about.intro': 'वेदरGPT एक AI आधारित मौसम प्लेटफॉर्म है जो मौसम की जानकारी को समझना और उपयोग करना आसान बनाता है।', 'about.detail': 'जटिल मौसम डेटा के बजाय वेदरGPT पूर्वानुमान, चेतावनी, स्थान की जानकारी, जलवायु और बातचीत को एक सरल प्लेटफॉर्म में लाता है।', 'about.what': 'वेदरGPT से आप क्या कर सकते हैं', 'about.forecasts': 'मौसम का पूर्वानुमान देखें', 'about.forecastsBody': 'अपने स्थान का वर्तमान मौसम और आने वाला पूर्वानुमान देखें।', 'about.questions': 'मौसम के सवाल पूछें', 'about.questionsBody': 'बारिश, कपड़े, यात्रा या सुरक्षा के बारे में सरल शब्दों में पूछें।', 'about.locations': 'स्थान के अनुसार मौसम', 'about.locationsBody': 'स्थान चुनकर मौसम और जोखिम की जानकारी पाएँ।', 'about.alerts': 'मौसम की चेतावनी से सतर्क रहें', 'about.alertsBody': 'गंभीर मौसम और संभावित खतरों की जानकारी पाएँ।', 'about.maps': 'नक्शे पर मौसम देखें', 'about.mapsBody': 'नक्शे पर जगहें और वहाँ का मौसम समझें।', 'about.climate': 'जलवायु की जानकारी पाएँ', 'about.climateBody': 'जलवायु, बारिश, मौसम और अन्य जानकारी सीखें।', 'about.designed': 'आपके लिए बनाया गया', 'about.designedBody': 'वेदरGPT जटिल मौसम जानकारी को साफ़ और उपयोगी सलाह में बदलता है।', 'about.designedBody2': 'दिन की योजना, यात्रा या बदलते मौसम को समझने में वेदरGPT मदद करता है।', 'about.vision': 'हमारा लक्ष्य', 'about.visionQuote': 'मौसम की जानकारी सभी के लिए सरल, सुलभ और उपयोगी बनाना।', 'about.visionBody': 'वेदरGPT विश्वसनीय मौसम जानकारी को बातचीत के रूप में देता है ताकि निर्णय लेना आसान हो।', 'about.footer': 'वेदरGPT - मौसम समझें, आत्मविश्वास से योजना बनाएँ।',
    'footer.climateData': 'जलवायु डेटा: Open-Meteo ऐतिहासिक मौसम API (ERA5)', 'footer.aiDetail': 'Google Gemini उपलब्ध होने पर; अन्यथा वेदरGPT नियम आधारित तरीका', 'footer.safety': 'सुरक्षा जानकारी', 'footer.safetyAutomated': 'स्वचालित आकलन आधिकारिक चेतावनी नहीं हैं।', 'footer.safetyAuthorities': 'गंभीर मौसम में स्थानीय अधिकारियों के निर्देश मानें।', 'footer.safetyIndia': 'भारत में IMD और NDMA की जानकारी देखें।',
  },
  kn: {
    'about.badge': 'ವೆದರ್GPT ಕುರಿತು', 'about.title': 'ಹವಾಮಾನ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ನಿಮ್ಮ ಬುದ್ಧಿವಂತ ಸಹಾಯಕ', 'about.intro': 'ವೆದರ್GPT ಹವಾಮಾನ ಮಾಹಿತಿಯನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ಸುಲಭವಾಗಿಸುವ AI ಹವಾಮಾನ ವೇದಿಕೆ.', 'about.detail': 'ಸಂಕೀರ್ಣ ಡೇಟಾದ ಬದಲು ಮುನ್ಸೂಚನೆ, ಎಚ್ಚರಿಕೆ, ಸ್ಥಳ ಮಾಹಿತಿ, ಹವಾಮಾನ ಮತ್ತು ಸಂಭಾಷಣೆಯನ್ನು ಒಂದೇ ವೇದಿಕೆಯಲ್ಲಿ ನೀಡುತ್ತದೆ.', 'about.what': 'ವೆದರ್GPT ನಲ್ಲಿ ನೀವು ಏನು ಮಾಡಬಹುದು', 'about.forecasts': 'ಹವಾಮಾನ ಮುನ್ಸೂಚನೆ ಪಡೆಯಿರಿ', 'about.forecastsBody': 'ನಿಮ್ಮ ಸ್ಥಳದ ಈಗಿನ ಹವಾಮಾನ ಮತ್ತು ಮುಂದಿನ ಮುನ್ಸೂಚನೆ ನೋಡಿ.', 'about.questions': 'ಹವಾಮಾನ ಪ್ರಶ್ನೆ ಕೇಳಿ', 'about.questionsBody': 'ಮಳೆ, ಬಟ್ಟೆ, ಪ್ರಯಾಣ ಅಥವಾ ಸುರಕ್ಷತೆ ಬಗ್ಗೆ ಸರಳವಾಗಿ ಕೇಳಿ.', 'about.locations': 'ಸ್ಥಳ ಆಧಾರಿತ ಹವಾಮಾನ', 'about.locationsBody': 'ಸ್ಥಳ ಆಯ್ಕೆ ಮಾಡಿ ಹವಾಮಾನ ಮತ್ತು ಅಪಾಯ ಮಾಹಿತಿ ಪಡೆಯಿರಿ.', 'about.alerts': 'ಹವಾಮಾನ ಎಚ್ಚರಿಕೆ ತಿಳಿಯಿರಿ', 'about.alertsBody': 'ತೀವ್ರ ಹವಾಮಾನ ಮತ್ತು ಅಪಾಯಗಳ ಮಾಹಿತಿಯನ್ನು ಪಡೆಯಿರಿ.', 'about.maps': 'ನಕ್ಷೆಯಲ್ಲಿ ಹವಾಮಾನ ನೋಡಿ', 'about.mapsBody': 'ನಕ್ಷೆಯಲ್ಲಿ ಸ್ಥಳಗಳನ್ನು ಮತ್ತು ಅಲ್ಲಿನ ಹವಾಮಾನವನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.', 'about.climate': 'ಹವಾಮಾನ ಮಾಹಿತಿ ತಿಳಿಯಿರಿ', 'about.climateBody': 'ಹವಾಮಾನ, ಮಳೆ, ಋತುಗಳು ಮತ್ತು ಇತರ ಮಾಹಿತಿಯನ್ನು ತಿಳಿಯಿರಿ.', 'about.designed': 'ನಿಮಗಾಗಿ ವಿನ್ಯಾಸಗೊಳಿಸಲಾಗಿದೆ', 'about.designedBody': 'ವೆದರ್GPT ಸಂಕೀರ್ಣ ಹವಾಮಾನ ಮಾಹಿತಿಯನ್ನು ಸ್ಪಷ್ಟ ಮತ್ತು ಉಪಯುಕ್ತ ಸಲಹೆಯಾಗಿ ಮಾಡುತ್ತದೆ.', 'about.designedBody2': 'ದಿನದ ಯೋಜನೆ, ಪ್ರಯಾಣ ಅಥವಾ ಬದಲಾಗುವ ಹವಾಮಾನವನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.', 'about.vision': 'ನಮ್ಮ ದೃಷ್ಟಿ', 'about.visionQuote': 'ಹವಾಮಾನ ಮಾಹಿತಿಯನ್ನು ಎಲ್ಲರಿಗೂ ಸರಳ, ಸುಲಭ ಮತ್ತು ಉಪಯುಕ್ತಗೊಳಿಸುವುದು.', 'about.visionBody': 'ವಿಶ್ವಾಸಾರ್ಹ ಹವಾಮಾನ ಮಾಹಿತಿಯನ್ನು ಸಂಭಾಷಣೆಯ ರೂಪದಲ್ಲಿ ನೀಡಿ ಉತ್ತಮ ನಿರ್ಧಾರಕ್ಕೆ ಸಹಾಯ ಮಾಡುತ್ತದೆ.', 'about.footer': 'ವೆದರ್GPT - ಹವಾಮಾನ ಅರ್ಥಮಾಡಿಕೊಂಡು ಆತ್ಮವಿಶ್ವಾಸದಿಂದ ಯೋಜಿಸಿ.',
    'footer.climateData': 'ಹವಾಮಾನ ಡೇಟಾ: Open-Meteo ಐತಿಹಾಸಿಕ ಹವಾಮಾನ API (ERA5)', 'footer.aiDetail': 'Google Gemini ಲಭ್ಯವಿದ್ದಾಗ; ಇಲ್ಲದಿದ್ದರೆ ವೆದರ್GPT ನಿಯಮ ಆಧಾರಿತ ವಿಧಾನ', 'footer.safety': 'ಸುರಕ್ಷತಾ ಮಾಹಿತಿ', 'footer.safetyAutomated': 'ಸ್ವಯಂಚಾಲಿತ ಮೌಲ್ಯಮಾಪನ ಅಧಿಕೃತ ಎಚ್ಚರಿಕೆಗಳಲ್ಲ.', 'footer.safetyAuthorities': 'ತೀವ್ರ ಹವಾಮಾನದಲ್ಲಿ ಸ್ಥಳೀಯ ಅಧಿಕಾರಿಗಳ ಸೂಚನೆ ಪಾಲಿಸಿ.', 'footer.safetyIndia': 'ಭಾರತದಲ್ಲಿ IMD ಮತ್ತು NDMA ಮಾಹಿತಿಯನ್ನು ನೋಡಿ.',
  },
  te: {
    'about.badge': 'వెదర్GPT గురించి', 'about.title': 'వాతావరణాన్ని అర్థం చేసుకోవడానికి మీ తెలివైన సహాయకుడు', 'about.intro': 'వెదర్GPT వాతావరణ సమాచారాన్ని సులభంగా అర్థం చేసుకునే AI వేదిక.', 'about.detail': 'సంక్లిష్ట డేటాకు బదులుగా సూచనలు, హెచ్చరికలు, ప్రదేశ సమాచారం, వాతావరణం మరియు సంభాషణను ఒకే చోట అందిస్తుంది.', 'about.what': 'వెదర్GPTతో మీరు చేయగలిగేవి', 'about.forecasts': 'వాతావరణ సూచనలు పొందండి', 'about.forecastsBody': 'మీ ప్రదేశం యొక్క ప్రస్తుత వాతావరణం మరియు రాబోయే సూచన చూడండి.', 'about.questions': 'వాతావరణ ప్రశ్నలు అడగండి', 'about.questionsBody': 'వర్షం, దుస్తులు, ప్రయాణం లేదా భద్రత గురించి సులభంగా అడగండి.', 'about.locations': 'ప్రదేశం ఆధారిత వాతావరణం', 'about.locationsBody': 'ప్రదేశాన్ని ఎంచుకుని వాతావరణం మరియు ప్రమాద సమాచారం పొందండి.', 'about.alerts': 'వాతావరణ హెచ్చరికలు తెలుసుకోండి', 'about.alertsBody': 'తీవ్రమైన వాతావరణం మరియు ప్రమాదాల సమాచారం పొందండి.', 'about.maps': 'మ్యాప్‌లో వాతావరణం చూడండి', 'about.mapsBody': 'మ్యాప్‌లో ప్రదేశాలను మరియు అక్కడి వాతావరణాన్ని అర్థం చేసుకోండి.', 'about.climate': 'వాతావరణ సమాచారం తెలుసుకోండి', 'about.climateBody': 'వాతావరణం, వర్షం, కాలాలు మరియు ఇతర సమాచారాన్ని తెలుసుకోండి.', 'about.designed': 'మీ కోసం రూపొందించబడింది', 'about.designedBody': 'వెదర్GPT సంక్లిష్ట వాతావరణ సమాచారాన్ని స్పష్టమైన సలహాగా మారుస్తుంది.', 'about.designedBody2': 'రోజు ప్రణాళిక, ప్రయాణం లేదా మారుతున్న వాతావరణాన్ని అర్థం చేసుకోవడంలో సహాయపడుతుంది.', 'about.vision': 'మా లక్ష్యం', 'about.visionQuote': 'వాతావరణ సమాచారాన్ని అందరికీ సులభంగా మరియు ఉపయోగకరంగా చేయడం.', 'about.visionBody': 'నమ్మకమైన వాతావరణ సమాచారాన్ని సంభాషణ రూపంలో అందించి మంచి నిర్ణయాలకు సహాయపడుతుంది.', 'about.footer': 'వెదర్GPT - వాతావరణాన్ని అర్థం చేసుకుని నమ్మకంగా ప్రణాళిక చేయండి.',
    'footer.climateData': 'వాతావరణ డేటా: Open-Meteo చారిత్రక వాతావరణ API (ERA5)', 'footer.aiDetail': 'Google Gemini అందుబాటులో ఉన్నప్పుడు; లేకపోతే వెదర్GPT నియమ ఆధారిత విధానం', 'footer.safety': 'భద్రతా సమాచారం', 'footer.safetyAutomated': 'ఆటోమేటిక్ అంచనాలు అధికారిక హెచ్చరికలు కావు.', 'footer.safetyAuthorities': 'తీవ్రమైన వాతావరణంలో స్థానిక అధికారుల సూచనలు పాటించండి.', 'footer.safetyIndia': 'భారతదేశంలో IMD మరియు NDMA నవీకరణలు చూడండి.',
  },
  ta: {
    'about.badge': 'வெதர்GPT பற்றி', 'about.title': 'வானிலையைப் புரிந்துகொள்ளும் உங்கள் அறிவார்ந்த துணை', 'about.intro': 'வெதர்GPT வானிலை தகவலை எளிதாகப் புரிந்துகொள்ள உதவும் AI தளம்.', 'about.detail': 'சிக்கலான தரவுக்கு பதிலாக முன்னறிவிப்பு, எச்சரிக்கை, இட தகவல், காலநிலை மற்றும் உரையாடலை ஒரே இடத்தில் வழங்குகிறது.', 'about.what': 'வெதர்GPT மூலம் நீங்கள் செய்யக்கூடியவை', 'about.forecasts': 'வானிலை முன்னறிவிப்பைப் பெறுங்கள்', 'about.forecastsBody': 'உங்கள் இடத்தின் தற்போதைய வானிலையையும் அடுத்த முன்னறிவிப்பையும் பாருங்கள்.', 'about.questions': 'வானிலை கேள்விகளைக் கேளுங்கள்', 'about.questionsBody': 'மழை, உடை, பயணம் அல்லது பாதுகாப்பு பற்றி எளிதாகக் கேளுங்கள்.', 'about.locations': 'இடத்தை அடிப்படையாகக் கொண்ட வானிலை', 'about.locationsBody': 'இடத்தைத் தேர்ந்தெடுத்து வானிலை மற்றும் ஆபத்து தகவலைப் பெறுங்கள்.', 'about.alerts': 'வானிலை எச்சரிக்கைகளை அறியுங்கள்', 'about.alertsBody': 'கடுமையான வானிலை மற்றும் ஆபத்துகள் பற்றிய தகவலைப் பெறுங்கள்.', 'about.maps': 'வரைபடத்தில் வானிலையைப் பாருங்கள்', 'about.mapsBody': 'வரைபடத்தில் இடங்களையும் அவற்றின் வானிலையையும் புரிந்துகொள்ளுங்கள்.', 'about.climate': 'காலநிலை தகவலை அறியுங்கள்', 'about.climateBody': 'காலநிலை, மழை, பருவங்கள் மற்றும் பிற தகவல்களை அறியுங்கள்.', 'about.designed': 'உங்களுக்காக உருவாக்கப்பட்டது', 'about.designedBody': 'சிக்கலான வானிலை தகவலை தெளிவான பயனுள்ள ஆலோசனையாக மாற்றுகிறது.', 'about.designedBody2': 'நாள் திட்டமிடல், பயணம் அல்லது மாறும் வானிலையைப் புரிந்துகொள்ள உதவுகிறது.', 'about.vision': 'எங்கள் நோக்கம்', 'about.visionQuote': 'வானிலை தகவலை அனைவருக்கும் எளிமையாகவும் பயனுள்ளதாகவும் மாற்றுவது.', 'about.visionBody': 'நம்பகமான வானிலை தகவலை உரையாடல் வடிவில் வழங்கி நல்ல முடிவுகளுக்கு உதவுகிறது.', 'about.footer': 'வெதர்GPT - வானிலையைப் புரிந்து நம்பிக்கையுடன் திட்டமிடுங்கள்.',
    'footer.climateData': 'காலநிலை தரவு: Open-Meteo வரலாற்று வானிலை API (ERA5)', 'footer.aiDetail': 'Google Gemini கிடைக்கும் போது; இல்லையெனில் வெதர்GPT விதி அடிப்படையிலான முறை', 'footer.safety': 'பாதுகாப்பு தகவல்', 'footer.safetyAutomated': 'தானியங்கி மதிப்பீடுகள் அதிகாரப்பூர்வ எச்சரிக்கைகள் அல்ல.', 'footer.safetyAuthorities': 'கடுமையான வானிலையில் உள்ளூர் அதிகாரிகளின் அறிவுரையைப் பின்பற்றுங்கள்.', 'footer.safetyIndia': 'இந்தியாவில் IMD மற்றும் NDMA தகவல்களைப் பாருங்கள்.',
  },
  ml: {
    'about.badge': 'WeatherGPT-നെ കുറിച്ച്', 'about.title': 'കാലാവസ്ഥ മനസ്സിലാക്കാനുള്ള നിങ്ങളുടെ ബുദ്ധിമാനായ സഹായി', 'about.intro': 'കാലാവസ്ഥാ വിവരങ്ങൾ എളുപ്പം മനസ്സിലാക്കാൻ സഹായിക്കുന്ന AI പ്ലാറ്റ്ഫോമാണ് WeatherGPT.', 'about.detail': 'സങ്കീർണ്ണമായ ഡാറ്റയ്ക്ക് പകരം പ്രവചനവും മുന്നറിയിപ്പുകളും സ്ഥല വിവരവും കാലാവസ്ഥാ അറിവും സംഭാഷണവും ഒരിടത്ത് നൽകുന്നു.', 'about.what': 'WeatherGPT ഉപയോഗിച്ച് ചെയ്യാവുന്ന കാര്യങ്ങൾ', 'about.forecasts': 'കാലാവസ്ഥാ പ്രവചനം നേടുക', 'about.forecastsBody': 'നിങ്ങളുടെ സ്ഥലത്തെ ഇപ്പോഴത്തെ കാലാവസ്ഥയും വരാനിരിക്കുന്ന പ്രവചനവും കാണുക.', 'about.questions': 'കാലാവസ്ഥാ ചോദ്യങ്ങൾ ചോദിക്കുക', 'about.questionsBody': 'മഴ, വസ്ത്രം, യാത്ര അല്ലെങ്കിൽ സുരക്ഷയെക്കുറിച്ച് ലളിതമായി ചോദിക്കുക.', 'about.locations': 'സ്ഥലം അടിസ്ഥാനമാക്കിയുള്ള കാലാവസ്ഥ', 'about.locationsBody': 'സ്ഥലം തിരഞ്ഞെടുത്ത് കാലാവസ്ഥയും അപകട വിവരവും നേടുക.', 'about.alerts': 'കാലാവസ്ഥാ മുന്നറിയിപ്പുകൾ അറിയുക', 'about.alertsBody': 'കഠിനമായ കാലാവസ്ഥയെയും അപകടങ്ങളെയും കുറിച്ചുള്ള വിവരങ്ങൾ നേടുക.', 'about.maps': 'മാപ്പിൽ കാലാവസ്ഥ കാണുക', 'about.mapsBody': 'മാപ്പിൽ സ്ഥലങ്ങളും അവിടത്തെ കാലാവസ്ഥയും മനസ്സിലാക്കുക.', 'about.climate': 'കാലാവസ്ഥാ വിവരം അറിയുക', 'about.climateBody': 'കാലാവസ്ഥ, മഴ, ഋതുക്കൾ, മറ്റ് വിവരങ്ങൾ എന്നിവ പഠിക്കുക.', 'about.designed': 'നിങ്ങൾക്കായി രൂപകൽപ്പന ചെയ്തത്', 'about.designedBody': 'സങ്കീർണ്ണമായ കാലാവസ്ഥാ വിവരങ്ങളെ വ്യക്തമായ ഉപദേശമാക്കി മാറ്റുന്നു.', 'about.designedBody2': 'ദിവസം ആസൂത്രണം ചെയ്യാനും യാത്രയ്ക്കും മാറുന്ന കാലാവസ്ഥ മനസ്സിലാക്കാനും സഹായിക്കുന്നു.', 'about.vision': 'ഞങ്ങളുടെ കാഴ്ചപ്പാട്', 'about.visionQuote': 'കാലാവസ്ഥാ വിവരങ്ങൾ എല്ലാവർക്കും ലളിതവും ലഭ്യവും പ്രയോജനകരവുമാക്കുക.', 'about.visionBody': 'വിശ്വസനീയമായ കാലാവസ്ഥാ വിവരങ്ങൾ സംഭാഷണ രൂപത്തിൽ നൽകി നല്ല തീരുമാനങ്ങൾക്ക് സഹായിക്കുന്നു.', 'about.footer': 'WeatherGPT - കാലാവസ്ഥ മനസ്സിലാക്കി ആത്മവിശ്വാസത്തോടെ ആസൂത്രണം ചെയ്യൂ.',
    'footer.climateData': 'കാലാവസ്ഥാ ഡാറ്റ: Open-Meteo ചരിത്ര കാലാവസ്ഥാ API (ERA5)', 'footer.aiDetail': 'Google Gemini ലഭ്യമെങ്കിൽ; അല്ലെങ്കിൽ WeatherGPT നിയമാധിഷ്ഠിത രീതി', 'footer.safety': 'സുരക്ഷാ വിവരം', 'footer.safetyAutomated': 'സ്വയമേവയുള്ള വിലയിരുത്തലുകൾ ഔദ്യോഗിക മുന്നറിയിപ്പുകളല്ല.', 'footer.safetyAuthorities': 'കഠിനമായ കാലാവസ്ഥയിൽ പ്രാദേശിക അധികാരികളുടെ നിർദ്ദേശങ്ങൾ പാലിക്കുക.', 'footer.safetyIndia': 'ഇന്ത്യയിൽ IMD, NDMA വിവരങ്ങൾ പരിശോധിക്കുക.',
  },
  mr: {
    'about.badge': 'वेदरGPT बद्दल', 'about.title': 'हवामान समजून घेण्यासाठी तुमचा बुद्धिमान साथी', 'about.intro': 'वेदरGPT हे हवामानाची माहिती सोप्या पद्धतीने समजून घेण्यासाठी AI व्यासपीठ आहे.', 'about.detail': 'कठीण डेटाऐवजी अंदाज, इशारे, स्थान माहिती, हवामान आणि संवाद एकाच ठिकाणी मिळतो.', 'about.what': 'वेदरGPT द्वारे तुम्ही काय करू शकता', 'about.forecasts': 'हवामानाचा अंदाज मिळवा', 'about.forecastsBody': 'तुमच्या ठिकाणचे सध्याचे हवामान आणि पुढील अंदाज पाहा.', 'about.questions': 'हवामानाचे प्रश्न विचारा', 'about.questionsBody': 'पाऊस, कपडे, प्रवास किंवा सुरक्षिततेबद्दल सोप्या शब्दांत विचारा.', 'about.locations': 'स्थानानुसार हवामान माहिती', 'about.locationsBody': 'स्थान निवडून हवामान आणि जोखीम माहिती मिळवा.', 'about.alerts': 'हवामानाच्या इशाऱ्यांपासून सावध रहा', 'about.alertsBody': 'तीव्र हवामान आणि संभाव्य धोक्यांची माहिती मिळवा.', 'about.maps': 'नकाशावर हवामान पाहा', 'about.mapsBody': 'नकाशावर ठिकाणे आणि तेथील हवामान समजून घ्या.', 'about.climate': 'हवामानाची माहिती जाणून घ्या', 'about.climateBody': 'हवामान, पाऊस, ऋतू आणि इतर माहिती जाणून घ्या.', 'about.designed': 'तुमच्यासाठी तयार केलेले', 'about.designedBody': 'कठीण हवामान माहितीचे स्पष्ट आणि उपयोगी सल्ल्यात रूपांतर करते.', 'about.designedBody2': 'दिवसाचे नियोजन, प्रवास किंवा बदलते हवामान समजून घेण्यास मदत करते.', 'about.vision': 'आमचे ध्येय', 'about.visionQuote': 'हवामानाची माहिती सर्वांसाठी सोपी, उपलब्ध आणि उपयोगी करणे.', 'about.visionBody': 'विश्वसनीय हवामान माहिती संवादाच्या रूपात देऊन चांगले निर्णय घेण्यास मदत करते.', 'about.footer': 'वेदरGPT - हवामान समजून आत्मविश्वासाने नियोजन करा.',
    'footer.climateData': 'हवामान डेटा: Open-Meteo ऐतिहासिक हवामान API (ERA5)', 'footer.aiDetail': 'Google Gemini उपलब्ध असल्यास; अन्यथा वेदरGPT नियम आधारित पद्धत', 'footer.safety': 'सुरक्षा माहिती', 'footer.safetyAutomated': 'स्वयंचलित मूल्यांकन अधिकृत इशारे नाहीत.', 'footer.safetyAuthorities': 'तीव्र हवामानात स्थानिक अधिकाऱ्यांच्या सूचनांचे पालन करा.', 'footer.safetyIndia': 'भारतात IMD आणि NDMA ची माहिती पाहा.',
  },
};
